### ISSUE TITLE
초기환경 설정셋팅

### ISSUE THREAD

**Issue by gogoyong** [gogoyong/electron#1]
## Description
프로젝트 초기환경 설정셋팅

## Todo List
- [x] 이슈, pr 템플릿 파일추가
- [x] wiki에 커밋 규칙 작성, eslint, prettier 설정
- [x] git flow를 활용한 develop branch 분기, 작업

## Estimated Time
1시간
